use std::sync::Arc;

use serde::{Deserialize, Serialize};
use strum::{EnumIter, EnumString, IntoStaticStr};

#[derive(
    Debug, PartialEq, Eq, Copy, Clone, EnumIter, EnumString, IntoStaticStr, Serialize, Deserialize,
)]
#[strum(serialize_all = "snake_case")]
pub enum IconName {
    AcpRegistry,
    AiAnthropic,
    AiAnthropicCompat,
    AiBedrock,
    AiClaude,
    AiDeepSeek,
    AiEdit,
    AiGemini,
    AiGoogle,
    AiLlamaCpp,
    AiLmStudio,
    AiMistral,
    AiOllama,
    AiOpenAi,
    AiOpenAiCompat,
    AiOpenAiGptSub,
    AiOpenCode,
    AiOpenRouter,
    AiVercel,
    AiXAi,
    AiZed,
    Archive,
    ArrowCircle,
    ArrowDown,
    ArrowDown10,
    ArrowDownRight,
    ArrowLeft,
    ArrowRight,
    ArrowRightLeft,
    ArrowUp,
    ArrowUpRight,
    AtSign,
    Attach,
    AudioOff,
    AudioOn,
    Backspace,
    Bell,
    BellDot,
    BellOff,
    BellRing,
    Binary,
    Bitbucket,
    Blocks,
    Bookmark,
    BoltFilled,
    BoltOutlined,
    Book,
    BookCopy,
    Box,
    BoxOpen,
    CaseSensitive,
    Chat,
    Check,
    CheckDouble,
    ChevronDown,
    ChevronDownUp,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronUpDown,
    Circle,
    CircleHelp,
    Clock,
    Close,
    CloudDownload,
    Code,
    Codeberg,
    Command,
    Compact,
    Control,
    Copilot,
    CopilotDisabled,
    CopilotError,
    CopilotInit,
    Copy,
    CountdownTimer,
    Crosshair,
    CursorIBeam,
    Dash,
    DatabaseZap,
    Debug,
    DebugBreakpoint,
    DebugContinue,
    DebugContinueThread,
    DebugDetach,
    DebugDisabledBreakpoint,
    DebugDisabledLogBreakpoint,
    DebugIgnoreBreakpoints,
    DebugLogBreakpoint,
    DebugPause,
    DebugStepInto,
    DebugStepOut,
    DebugStepOver,
    Diff,
    DiffSplit,
    DiffSplitAuto,
    DiffUnified,
    Disconnected,
    Download,
    EditorAtom,
    EditorCursor,
    EditorEmacs,
    EditorJetBrains,
    EditorSublime,
    EditorVsCode,
    Ellipsis,
    Envelope,
    Eraser,
    Escape,
    Exit,
    ExpandDown,
    ExpandUp,
    ExpandVertical,
    Eye,
    EyeOff,
    FastForward,
    FastForwardOff,
    File,
    FileCode,
    FileCodeOff,
    FileDiff,
    FileDoc,
    FileGeneric,
    FileGit,
    FileIgnored,
    FileLock,
    FileMarkdown,
    FileMultiple,
    FileRust,
    FileTextFilled,
    FileTextOutlined,
    FileToml,
    FileTree,
    Filter,
    FilterFunnel,
    Flame,
    FoldVertical,
    Folder,
    FolderAdd,
    FolderInclude,
    FolderOpen,
    FolderSearch,
    FolderShare,
    FolderShared,
    Font,
    FontSize,
    FontWeight,
    Forgejo,
    ForwardArrow,
    ForwardArrowUp,
    GenericClose,
    GenericMaximize,
    GenericMinimize,
    GenericRestore,
    Gerrit,
    GitBranch,
    GitBranchPlus,
    GitCommit,
    GitGraph,
    GitMergeConflict,
    GitWorktree,
    Gitea,
    Github,
    Gitlab,
    Hash,
    HistoryRerun,
    Image,
    Inception,
    Indicator,
    Info,
    Json,
    Keyboard,
    LineHeight,
    Link,
    Linux,
    ListCollapse,
    ListTodo,
    ListTree,
    ListX,
    LoadCircle,
    /// Brainz: rocket used by the agent/shell launcher.
    Launch,
    /// Brainz: calendar tab button.
    BrainzCalendar,
    /// Brainz: MCP connectors tab button.
    BrainzMcp,
    BrainzTheme,
    /// Brainz: sliders used for the composer's model/mode options toggle.
    BrainzSliders,
    /// Brainz: open to-do item (rounded square).
    BrainzCheckboxEmpty,
    /// Brainz: done to-do item (rounded square with a check).
    BrainzCheckboxChecked,
    /// Brainz: Claude mark (from the ACP registry).
    BrainzClaude,
    /// Brainz: Codex mark (from the ACP registry).
    BrainzCodex,
    /// Brainz: filled rounded square used as a tab colour swatch.
    Swatch,
    LocationEdit,
    Lock,
    LockOff,
    MagnifyingGlass,
    Maximize,
    MaximizeAlt,
    Menu,
    Mic,
    MicMute,
    Minimize,
    Notepad,
    OnCall,
    Option,
    PageDown,
    PageUp,
    Paperclip,
    Pencil,
    PencilUnavailable,
    Person,
    Pin,
    PlayFilled,
    PlayOutlined,
    Plus,
    Power,
    Public,
    PullRequest,
    QueueMessage,
    Quote,
    Reader,
    RefreshTitle,
    Regex,
    ReplNeutral,
    Replace,
    ReplaceAll,
    ReplaceNext,
    ReplyArrowRight,
    Rerun,
    Return,
    RotateCcw,
    RotateCw,
    Scissors,
    Screen,
    SelectAll,
    Send,
    Server,
    Settings,
    Share,
    Shift,
    SignalHigh,
    SignalLow,
    SignalMedium,
    Slash,
    Sourcehut,
    Space,
    Sparkle,
    Split,
    SplitAlt,
    SquareDot,
    SquareMinus,
    SquarePlus,
    Star,
    StarFilled,
    Stop,
    Tab,
    Table,
    Terminal,
    TerminalAlt,
    TextSnippet,
    TextWrap,
    TextUnwrap,
    ThinkingMode,
    ThinkingModeOff,
    ThisWindow,
    Thread,
    ThreadFromSummary,
    ThreadsSidebarLeftClosed,
    ThreadsSidebarLeftOpen,
    ThreadsSidebarRightClosed,
    ThreadsSidebarRightOpen,
    ThumbsDown,
    ThumbsUp,
    TodoComplete,
    TodoPending,
    TodoProgress,
    ToolCopy,
    ToolDeleteFile,
    ToolDiagnostics,
    ToolHammer,
    ToolNotification,
    ToolPencil,
    ToolSearch,
    ToolTerminal,
    ToolThink,
    ToolWeb,
    Trash,
    Triangle,
    TriangleRight,
    Undo,
    Unpin,
    UserArrowUp,
    UserCheck,
    UserGroup,
    UserRoundPen,
    Warning,
    WholeWord,
    XCircle,
    XCircleFilled,
    ZedAgent,
    ZedAgentTwo,
    ZedAssistant,
    ZedPredict,
    ZedPredictDisabled,
    ZedPredictDown,
    ZedPredictError,
    ZedPredictUp,
    ZedSrcCustom,
    ZedSrcExtension,
}

impl IconName {
    /// Returns the path to this icon.
    pub fn path(&self) -> Arc<str> {
        match self {
            Self::MagnifyingGlass => return "icons/brainz/search.svg".into(),
            Self::Folder => return "icons/brainz/folder.svg".into(),
            Self::FolderOpen => return "icons/brainz/folder-open.svg".into(),
            Self::Terminal | Self::TerminalAlt => return "icons/brainz/terminal.svg".into(),
            Self::ArrowLeft => return "icons/brainz/back.svg".into(),
            Self::ArrowRight => return "icons/brainz/forward.svg".into(),
            Self::Check => return "icons/brainz/check.svg".into(),
            Self::Copy => return "icons/brainz/copy.svg".into(),
            Self::Launch => return "icons/brainz/launch.svg".into(),
            Self::BrainzCalendar => return "icons/brainz/calendar.svg".into(),
            Self::BrainzMcp => return "icons/brainz/mcp.svg".into(),
            Self::BrainzTheme => return "icons/brainz/theme.svg".into(),
            Self::BrainzClaude => return "icons/brainz/claude.svg".into(),
            Self::BrainzCodex => return "icons/brainz/codex.svg".into(),
            Self::Split => return "icons/brainz/split.svg".into(),
            Self::FileTree => return "icons/brainz/files.svg".into(),
            Self::Plus => return "icons/brainz/plus.svg".into(),
            Self::Close => return "icons/brainz/close.svg".into(),
            Self::Trash => return "icons/brainz/trash.svg".into(),
            Self::Send => return "icons/brainz/send.svg".into(),
            Self::Ellipsis => return "icons/brainz/ellipsis.svg".into(),
            Self::BrainzSliders => return "icons/brainz/sliders.svg".into(),
            Self::BrainzCheckboxEmpty => return "icons/brainz/checkbox-empty.svg".into(),
            Self::BrainzCheckboxChecked => return "icons/brainz/checkbox-checked.svg".into(),
            Self::Swatch => return "icons/brainz/swatch.svg".into(),
            Self::Maximize => return "icons/brainz/expand.svg".into(),
            Self::Minimize => return "icons/brainz/collapse.svg".into(),
            Self::File | Self::FileGeneric | Self::FileDoc | Self::FileMarkdown | Self::Book => {
                return "icons/brainz/file.svg".into();
            }
            _ => {}
        }
        let file_stem: &'static str = self.into();
        format!("icons/{file_stem}.svg").into()
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use strum::{IntoEnumIterator as _, ParseError};

    use crate::IconName;

    #[test]
    fn test_all_icons_exist() {
        let asset_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets");

        for icon in IconName::iter() {
            let icon_path = asset_path.join(&*icon.path());
            assert!(
                icon_path.exists(),
                "Icon {icon:?} does not exist at {icon_path:?}",
            );
        }
    }

    #[test]
    fn test_no_dangling_icons() -> Result<(), ParseError> {
        let icons_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../assets/icons");

        for entry in std::fs::read_dir(&icons_dir).expect("failed to read icons directory") {
            let path = entry.expect("failed to read icons directory entry").path();
            if path.extension().is_none_or(|extension| extension != "svg") {
                continue;
            }
            let file_stem = path
                .file_stem()
                .and_then(|file_stem| file_stem.to_str())
                .expect("icon file name is not valid UTF-8");

            file_stem.parse::<IconName>()?;
        }

        Ok(())
    }
}
